language: php
dist: trusty
sudo: required

php:
  - 7.4
  - nightly

services:
  - docker
before_install:
  - docker run -d -p 127.0.0.1:8123:8123 --name test-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server
  - docker ps -a
  - sed -i 's/localhost/clickhouse-server/' ./phpunit.xml.dist
  - echo '127.0.0.1 clickhouse-server' | sudo tee /etc/hosts > /dev/null

before_script:
  - composer install

script:
  - ./vendor/bin/phpunit --configuration ./phpunit.xml.dist

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
